services:
  scraper:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    container_name: scrape101-scraper-${BATCH_INDEX:-0}
    environment:
      - BATCH_INDEX=${BATCH_INDEX:-0}
      - BATCH_SIZE=${BATCH_SIZE:-25}
      - SEQUENTIAL=${SEQUENTIAL:-false}
    command: >
      sh -c "echo 'Environment variables loaded:' &&
             echo 'SUPABASE_URL: $SUPABASE_URL' &&
             echo 'BATCH_SIZE: $BATCH_SIZE' &&
             echo 'BATCH_INDEX: $BATCH_INDEX' &&
             playwright install chromium &&
             playwright install-deps &&
             python scraper_groq.py"
    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: "no"
    isolation: "default"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - scraper-network

networks:
  scraper-network:
    driver: bridge

