def get_tagging_prompts(content: str) -> dict:
    """Returns a dictionary of all tagging prompts with the content inserted."""
 
    # NEW DEEPSEEK PROMPT KEYS
    return {
        "long_offering": f"""Based strictly on the {content}, write a concise but detailed 4–5 sentence paragraph that clearly describes the company's offering.\n\nYour answer should cover:\nWhat the company primarily provides (main product or service, in simple functional terms)\nWho the product or service is meant for (the type of end users or business functions, without naming personas)\nThe core function or outcome the offering delivers (e.g., training, management, automation, analysis)\nThe business category or classification the offering falls under (e.g., learning software, analytics platform, compliance tool)\nThe delivery format or product model, if mentioned (e.g., SaaS, mobile app, consultancy)\n\nWrite in plain commercial language — avoid acronyms, technical details, adjectives, or use-case explanations. Do not list features or implementation methods.\n\nUse complete sentences and structured, factual tone. The goal is to generate a description that can later be split into tags, categories, and short-form summaries.""",
        "long_problem_solved": f"""Based strictly on the {content}, write a 3–4 sentence paragraph that clearly describes the main business problems the company helps solve for its customers. \n\nYour response should include: \nThe broad operational or strategic challenges the company helps its customers address (e.g., inefficiency, inconsistency, low productivity) \nThe specific customer pain points the offering is designed to solve (e.g., poor coaching visibility, disconnected training programs, slow onboarding) \nThe commercial or outcome-based impact of solving these problems (e.g., increased team productivity, faster execution, improved compliance) \n\nFocus only on outcome-level issues the customer faces—not features, tech, or implementation methods. \n\nWrite in plain business language. Do not list features, buyer personas, internal language, or aspirational goals. No acronyms, no technical jargon.""",
        "long_use_cases": f"""Based strictly on the {content}, write a clear 3–4 sentence paragraph describing the main business use cases for the company's offering. \n\nYour response should cover: \nThe types of tasks or workflows the product or service is commonly used for \nThe business functions or departments where it is typically applied (e.g., sales, HR, compliance) \nThe practical outcomes the product enables (e.g., coaching delivery, performance tracking, compliance management) \nAny recurring patterns of use mentioned across case studies or customer examples \n\nWrite in plain commercial language that a non-technical audience can understand. Avoid acronyms, internal terminology, technical features, or buyer personas. \n\nThe goal is to describe how the product is used in practice, so it can be broken into specific tags, general statements, and task-focused descriptions.""",
        "target_customers_description": f"""Based strictly on the {content}, write a concise paragraph (2–3 sentences) describing the company's target customers. \n\nYour answer must be in natural language only (not bullet points, not JSON). \n\nInclude: \nThe types of organizations the company serves (e.g., large enterprises, mid-sized companies) \nThe industries these customers operate in, based on any client logos, testimonials, or case studies present on the site \nThe departments, teams, or roles they target (e.g., sales managers, field teams) \nThe operational goals or priorities these customers address with the company's offering (e.g., improving coaching, maximizing ROI, ensuring compliance) \n\nAvoid returning structured or nested data. Output only a clean, well-written paragraph suitable for display to end users.""",
        "customers_industries": f"""Based strictly on {content}, identify the industries or sectors that the company's customers belong to.\n\nUse all available evidence on the site—including customer logos, testimonials, case studies, named clients, or any sector-specific language—to determine the most likely industries the company serves.\n\nIf the industries are not explicitly stated, infer them based on the types of companies shown or referenced. For example, if logos include pharmaceutical or healthcare companies, infer "life sciences" or "healthcare" accordingly.\n\nReturn a short list of 2–4 customer industries using broad, commercially recognizable categories (e.g., financial services, life sciences, manufacturing, education).\n\nUse only lowercase and separate each industry with a semicolon. Do not list job titles, roles, use cases, or buyer types. Avoid vague terms like "various" or "diverse industries."\n\nExamples:\nlife sciences; pharmaceuticals; consumer goods\nfinancial services; insurance; banking""",
        "long_company_description": f"""Based on the {content}, generate the following output:  company_offering: "[Insert a clear, 3–5 sentence paragraph here describing the company's offering. This paragraph should include what the company provides, who they serve, their customer industries (based only on content), the purpose they solve, notable technologies, and how it's delivered. Use natural language, commercial tone. Do not include any nested objects or bullet points—just a plain paragraph in this field.]" """,
        "summary": f"""analyze the full content of the {content}.\nBased on the complete information available—across product descriptions, positioning, customer references, use cases, and messaging—generate a 3–5 sentence paragraph that clearly and comprehensively describes the business.\n\nWrite as if you are a senior go-to-market strategist or commercial due diligence advisor explaining the company's core business to an executive audience.\n\nYour paragraph should:\n\nSummarize what the company does (its core offering and capabilities)\nHighlight who it serves (types of organizations and roles)\nDescribe where and how it operates (e.g., geographies, industries, delivery model)\nIdentify the problem it solves or value it creates for its customers\n\nUse precise, professional business language. Avoid buzzwords, acronyms, or vague claims. Ensure your summary reflects clear insight and judgment, not just repetition of website copy."""
    } 



# System prompt for the LLM
SYSTEM_PROMPT = """You are a senior M&A analyst and ex-investment banker with deep experience in commercial due diligence and buyer targeting.
Your role is to analyze company websites and extract clear, structured business information for use in buy-side and sell-side M&A processes.
You focus on what the company actually does, how it delivers value, and in which domain — avoiding marketing language, vague benefits, or aspirational claims.
Your output is concise, analytical, and aligned with the information needs of investors and acquirers. You prioritize function over fluff, and always return structured, match-ready data that can support semantic scoring and deal logic — with no explanation.
Do include your thought process, just give the answers with no extra explanations or opinion.
Do not output introductions, analysis, features, or commentary
Return just result — no reasoning, no summary, no preamble.
"""

def get_return_prompts(llm_return):
    """
    Generate prompts for further analysis or summarization based on the LLM's return value.
    Args:
        llm_return (str): The output returned by the LLM.
    Returns:
        dict: A dictionary of prompts keyed by their intended analysis.
    """
    new_prompts = defaultdict(list)
    for key, value in llm_return.items():
        new_prompts[key].append(value)

