from collections import defaultdict

def get_tagging_prompts(content: str) -> dict:
    """Returns a dictionary of all tagging prompts with the content inserted."""
 
    # NEW DEEPSEEK PROMPT KEYS
    return {
        "long_offering": f"""Based strictly on the {content}, write a concise but detailed 4–5 sentence paragraph that clearly describes the company's offering.\n\nYour answer should cover:\nWhat the company primarily provides (main product or service, in simple functional terms)\nWho the product or service is meant for (the type of end users or business functions, without naming personas)\nThe core function or outcome the offering delivers (e.g., training, management, automation, analysis)\nThe business category or classification the offering falls under (e.g., learning software, analytics platform, compliance tool)\nThe delivery format or product model, if mentioned (e.g., SaaS, mobile app, consultancy)\n\nWrite in plain commercial language — avoid acronyms, technical details, adjectives, or use-case explanations. Do not list features or implementation methods.\n\nUse complete sentences and structured, factual tone. The goal is to generate a description that can later be split into tags, categories, and short-form summaries.""",
        "long_problem_solved": f"""Based strictly on the {content}, write a 3–4 sentence paragraph that clearly describes the main business problems the company helps solve for its customers. \n\nYour response should include: \nThe broad operational or strategic challenges the company helps its customers address (e.g., inefficiency, inconsistency, low productivity) \nThe specific customer pain points the offering is designed to solve (e.g., poor coaching visibility, disconnected training programs, slow onboarding) \nThe commercial or outcome-based impact of solving these problems (e.g., increased team productivity, faster execution, improved compliance) \n\nFocus only on outcome-level issues the customer faces—not features, tech, or implementation methods. \n\nWrite in plain business language. Do not list features, buyer personas, internal language, or aspirational goals. No acronyms, no technical jargon.""",
        "long_use_cases": f"""Based strictly on the {content}, write a clear 3–4 sentence paragraph describing the main business use cases for the company's offering. \n\nYour response should cover: \nThe types of tasks or workflows the product or service is commonly used for \nThe business functions or departments where it is typically applied (e.g., sales, HR, compliance) \nThe practical outcomes the product enables (e.g., coaching delivery, performance tracking, compliance management) \nAny recurring patterns of use mentioned across case studies or customer examples \n\nWrite in plain commercial language that a non-technical audience can understand. Avoid acronyms, internal terminology, technical features, or buyer personas. \n\nThe goal is to describe how the product is used in practice, so it can be broken into specific tags, general statements, and task-focused descriptions.""",
        "target_customers_description": f"""Based strictly on the {content}, write a concise paragraph (2–3 sentences) describing the company's target customers. \n\nYour answer must be in natural language only (not bullet points, not JSON). \n\nInclude: \nThe types of organizations the company serves (e.g., large enterprises, mid-sized companies) \nThe industries these customers operate in, based on any client logos, testimonials, or case studies present on the site \nThe departments, teams, or roles they target (e.g., sales managers, field teams) \nThe operational goals or priorities these customers address with the company's offering (e.g., improving coaching, maximizing ROI, ensuring compliance) \n\nAvoid returning structured or nested data. Output only a clean, well-written paragraph suitable for display to end users.""",
        "customers_industries": f"""Based strictly on {content}, identify the industries or sectors that the company's customers belong to.\n\nUse all available evidence on the site—including customer logos, testimonials, case studies, named clients, or any sector-specific language—to determine the most likely industries the company serves.\n\nIf the industries are not explicitly stated, infer them based on the types of companies shown or referenced. For example, if logos include pharmaceutical or healthcare companies, infer "life sciences" or "healthcare" accordingly.\n\nReturn a short list of 2–4 customer industries using broad, commercially recognizable categories (e.g., financial services, life sciences, manufacturing, education).\n\nUse only lowercase and separate each industry with a semicolon. Do not list job titles, roles, use cases, or buyer types. Avoid vague terms like "various" or "diverse industries."\n\nExamples:\nlife sciences; pharmaceuticals; consumer goods\nfinancial services; insurance; banking""",
        "long_company_description": f"""Based on the {content}, generate the following output:  company_offering: "[Insert a clear, 3–5 sentence paragraph here describing the company's offering. This paragraph should include what the company provides, who they serve, their customer industries (based only on content), the purpose they solve, notable technologies, and how it's delivered. Use natural language, commercial tone. Do not include any nested objects or bullet points—just a plain paragraph in this field.]" """,
        "summary": f"""analyze the full content of the {content}.\nBased on the complete information available—across product descriptions, positioning, customer references, use cases, and messaging—generate a 3–5 sentence paragraph that clearly and comprehensively describes the business.\n\nWrite as if you are a senior go-to-market strategist or commercial due diligence advisor explaining the company's core business to an executive audience.\n\nYour paragraph should:\n\nSummarize what the company does (its core offering and capabilities)\nHighlight who it serves (types of organizations and roles)\nDescribe where and how it operates (e.g., geographies, industries, delivery model)\nIdentify the problem it solves or value it creates for its customers\n\nUse precise, professional business language. Avoid buzzwords, acronyms, or vague claims. Ensure your summary reflects clear insight and judgment, not just repetition of website copy."""
    } 



# System prompt for the LLM
SYSTEM_PROMPT = """You are a senior M&A analyst and ex-investment banker with deep experience in commercial due diligence and buyer targeting.
Your role is to analyze company websites and extract clear, structured business information for use in buy-side and sell-side M&A processes.
You focus on what the company actually does, how it delivers value, and in which domain — avoiding marketing language, vague benefits, or aspirational claims.
Your output is concise, analytical, and aligned with the information needs of investors and acquirers. You prioritize function over fluff, and always return structured, match-ready data that can support semantic scoring and deal logic — with no explanation.
Do include your thought process, just give the answers with no extra explanations or opinion.
Do not output introductions, analysis, features, or commentary
Return just result — no reasoning, no summary, no preamble.
"""

def get_return_prompts(llm_return):
    """
    Generate prompts for further analysis or summarization based on the LLM's return value.
    Args:
        llm_return (dict): The output returned by the LLM, containing responses to initial prompts.
    Returns:
        dict: A dictionary of prompts keyed by their intended analysis, with the LLM's responses infused.
    """
    new_prompts = {}
    
    # For each category in PROMPTS
    for category, prompts in PROMPTS.items():
        new_prompts[category] = {}
        
        # For each prompt in the category
        for prompt_key, prompt_template in prompts.items():
            # Format the prompt template with the LLM's responses
            try:
                formatted_prompt = prompt_template.format(**llm_return)
                new_prompts[category][prompt_key] = formatted_prompt
            except KeyError as e:
                # Skip prompts that require keys not present in llm_return
                continue
            except Exception as e:
                # Handle any other formatting errors
                continue
    
    return new_prompts





PROMPTS = {
    "offering_match": {
        "category_tag": "Based on the {long_company_description} and {long_offering} and {summary}, return 2-3 tags that best describes the core business category of the company.\nDo not include use cases, buyer types, or technologies here. Use language a child can understand. Focus only on the primary result and put keywords first. Optimize the response for semantic search. Avoid use cases, buyer personas, or acronyms. Use lowercase, semicolon. Use language a child can understand.\nExamples: sales software, learning management system, compliance services, industrial equipment, data analytics",
        
        "offering_tag": "Based on the {long_company_description} and {long_offering} and {summary}, in pragmatic, commercial, and unambiguous structure 2-3 tags (2-5 words each) that best describes the primary product or service the company.\nDo not include use cases, buyer types, or technologies here. Use language a child can understand. Focus only on the primary result and put keywords first. Optimize the response for semantic search. Avoid use cases, buyer personas, or acronyms. Use lowercase, semicolon. Use language a child can understand.\nExamples: sales software, learning management system, compliance services, industrial equipment, data analytics",
        
        "short_sentence_broad": "Based on the {long_company_description} and {long_offering} and {summary}, in a single sentence, describe what the company provides by summarizing its core business deliverables using specific, functional terms. Focus on the primary products or services it offers to customers. Use broad categorisation when summarising the key information. Do not explain how the offerings work or include a detailed breakdown.\nAvoid use cases, buyer personas, or acronyms. Use language a child can understand. Avoid any jargon, avoid adjectives and limit function words.\nReturn the answer in the format of 1 short sentence, for example: \"Provides cloud-based business solutions.\"",
        
        "short_sentence_specific": "Based on the {long_company_description} and {long_offering} and {summary}, in a single sentence, describe what the company provides by summarizing its core business deliverables using specific, functional terms. Focus on the primary products or services it offers to customers. Use direct, commercial language for categorisation when summarising the key information. Do not explain how the offerings work or include a detailed breakdown.\nAvoid use cases, buyer personas, or acronyms. Use language a child can understand. Avoid any jargon, avoid adjectives and limit function words.\nReturn the answer in the format of 1 short sentence, for example: \"Provides cloud-based contract management solutions.\"",
        
        "categorisation_offering": "Based on the {long_company_description} and {long_offering} and {summary}, return two short sentences that describe what the company provides.\n• The first sentence should summarize the company's offering using a broad, functional categorisation — what type of business it is and the general product or service it offers. Keep it simple and category-based.\n• The second sentence should describe the specific offering, using direct, commercial language that reflects what the company actually delivers to customers. Use plain, functional terms that are easy to understand.\nAvoid acronyms, adjectives, feature descriptions, buyer personas, or technical explanations. Do not repeat or expand the first sentence. Use simple, factual language only.\nExamples: Provides software for employee training.\nOffers a platform for delivering and managing team-based learning programs.",
        
        "problem_tag": "Based on the {long_problem_solved}, list 2–3 short tags that describe the main problems or pain points the company solves for its customers. Focus only on primary, outcome-level issues. Use clear, compressed, keyword-rich phrases. No full sentences.\nDo not include features, technologies, or jargon. Avoid buyer personas. Use plain, everyday language. Use lowercase and separate tags with semicolons. Optimized for semantic search.\nExamples:\nmanual sales processes; slow employee onboarding; poor customer engagement",
        
        "problem_short_sentence_broad": "Based on the {long_problem_solved}, write 1 short sentence describing the broad business problem the company helps customers solve. Use general but functional terms that reflect key business challenges. Avoid detailed explanations, buyer types, or feature lists.\nUse clear, plain language — no jargon, acronyms, or buzzwords. One sentence only.\nExample:\nHelps businesses streamline training and development.",
        
        "problem_short_sentence_specific": "Based on the {long_problem_solved}, write 1 short sentence that describes the specific problem or pain point the company solves for its customers. Use commercial, outcome-focused language that reflects the actual challenge being addressed.\nAvoid describing how it works — just the result or issue being solved. No jargon, acronyms, or filler. One sentence only.\nExample:\nEliminates inefficiencies in field sales coaching and performance tracking.",
        
        "problem_combined": "Based on the {long_problem_solved}, return two short sentences that describe the core problems the company solves.\n• The first sentence should describe the broad challenge the company addresses across its market.\n• The second sentence should describe the specific pain point or outcome it helps fix in practical, commercial terms.\nAvoid repetition, feature lists, or internal terminology. Use simple language. Do not use buyer personas or acronyms.\nExample Output:\nHelps companies improve employee development at scale.\nSolves the challenge of delivering consistent coaching across large, dispersed sales teams.",
        
        "use_case_tag": "Based on the {long_use_cases}, list 2–3 tags that describe the primary use cases of the company's offering. Focus only on key applications or functions. Use clear, compressed, keyword-rich phrases. No full sentences.\nAvoid filler, features, technologies, or buyer personas. Use lowercase and separate tags with semicolons. Optimized for semantic search.\nExamples:\nmanaging employee performance; automating sales training; tracking compliance requirements",
        
        "use_case_short_sentence_broad": "Based on the {long_use_cases}, write 1 short sentence describing the general or high-level uses of the company's offering. Focus on what the product is generally used for, not how it works. Avoid use case details, personas, or feature mentions.\nUse simple, clear language with no jargon or acronyms.\nExample:\nUsed by businesses to improve team performance and operational efficiency.",
        
        "use_case_short_sentence_specific": "Based on the {long_use_cases}, write 1 short sentence that describes the specific way the company's offering is used. Focus on the practical task or workflow the product helps perform. Use plain commercial language.\nAvoid technical detail or explanations. No filler, no repetition.\nExample:\nUsed to deliver personalized sales coaching sessions across field teams.",
        
        "use_case_combined": "Based on the {long_use_cases}, return two short sentences that describe how the company's offering is used.\n• The first sentence should describe the broad business function or department where the offering is applied.\n• The second sentence should explain a specific use case or task the product enables.\nAvoid features, buzzwords, and personas. Use simple language only.\nExample Output:\nCommonly used by sales and training teams to support performance initiatives.\nEnables managers to track, assign, and deliver tailored coaching activities.",
        
        "customer_tag": "Based on the {target_customers_description} and {customers_industries}, list 2–3 concise tags that describe the key users of the product or service. Each tag must combine:\n1. The user role/team/department\n2. The main function or purpose of use\nUse direct, operational language. Avoid generic terms like \"business users\" or aspirational language. Do not list buyer personas or job titles alone — combine them with their core responsibility.\nUse lowercase, semicolon-separated tags. Optimize for semantic search.\nExamples:\nhr managers overseeing onboarding; sales teams managing pipeline; compliance officers conducting audits",
        
        "customer_short_sentence_broad": "Based on the {target_customers_description} and {customers_industries}, write 1 short sentence describing the general type of user who uses the product or service. Focus on teams or departments rather than individuals.\nUse clear language that reflects how a business unit would describe itself. No buzzwords, acronyms, or filler.\nExample:\nUsed by HR, sales, and compliance teams to manage core operational processes.",
        
        "customer_short_sentence_specific": "Based on the {target_customers_description} and {customers_industries}, write 1 short sentence describing the specific user role and their primary function using the product or service. Be precise. Include both the who and the why.\nAvoid generic phrases. Use practical, business-relevant language only.\nExample:\nUsed by field sales managers to deliver and monitor coaching programs across regional teams.",
        
        "customer_combined": "Based on the {target_customers_description} and {customers_industries}, return two short sentences describing who uses the product and what they do with it.\n• The first sentence should identify the general user segment or department.\n• The second sentence should describe the specific role and their operational purpose.\nUse simple, commercial phrasing. Avoid personas, feature references, or aspirational language.\nExample Output:\nThe product is used by sales enablement and HR teams.\nSales managers use it to guide, track, and improve rep performance through structured coaching programs.",
        
        "target_functional_category": "Based on the {long_company_description} and {long_offering} and {summary}, assign the company to up to three high-level functional categories that best describe what it actually does or delivers. These categories refer to core operational capabilities — i.e., what the company builds, delivers, or enables — not the industry it serves.\nUse only clearly stated or directly implied information. Do not infer future potential, edge features, or adjacent functions.\nReturn the selected categories as a semicolon-separated list using the exact names from the list below (no punctuation, no rewording). If only one clearly applies, return just that.\n\nFunctional Category List:\nengineering & manufacturing\nsupply chain & logistics\nproduct & lifecycle management\nsoftware & digital\nbusiness operations & admin\ncustomer sales & marketing\nfield services & deployment\nhealthcare & life sciences\neducation & training\nr&d testing & ip\nenergy utilities & infrastructure\nlegal & compliance\nenvironmental & sustainability\nreal estate & facilities\nretail & commerce",
        
        "target_commercial_category": "Based on the {long_company_description} and {long_offering} and {summary}, assign the company to one primary commercial category from the standardized list below.\nSelect the category that best reflects the company's core offering or its main real-world application — i.e., what it actually provides to the market today.\nUse only clearly stated or directly implied information. Do not infer future or minor use cases.\n\nCategory List (choose one only):\nEnterprise Software (e.g., HR platforms, CRM, ERP, procurement software)\nConsumer Products & Brands (e.g., wellness products, D2C clothing, personal gadgets)\nHealthcare & Life Sciences (e.g., diagnostics, mental health tools, medical devices, biotech)\nFinancial Services & Fintech (e.g., insurance platforms, payment processors, lending tech)\nIndustrial & Manufacturing (e.g., factory machinery, robotics, industrial automation tools)\nLogistics, Supply Chain & Mobility (e.g., delivery platforms, fleet management, freight systems)\nRetail & E-Commerce (e.g., online stores, marketplace platforms, POS systems)\nConstruction, Infrastructure & Real Estate (e.g., proptech, construction mgmt software, contractors)\nProfessional Services & Outsourcing (e.g., consulting firms, BPOs, legal or accounting services)\nEducation & Workforce Development (e.g., learning platforms, training tools, credentialing services)\nEnergy, Utilities & Cleantech (e.g., solar platforms, grid optimization, waste-to-energy tech)\nTelecom, Connectivity & IT Infrastructure (e.g., broadband services, edge networks, MSPs)\nCybersecurity & Risk Management (e.g., fraud detection, identity security, threat monitoring)\nMedia, Content & Advertising (e.g., adtech, content creation, audience analytics)\nHospitality, Travel & Experiences (e.g., booking platforms, hotels, events, tours)\nAgriculture & Food Systems (e.g., agtech, food processing, farming automation)\n\nReturn only the exact category name.",
        
        "product_service_tags": "Based on the {long_company_description} and {long_offering} and {summary}, list 1–3 short tags that describe what type of product or service the company provides.\nFocus on the category it fits into — such as:\nsales coaching platform, learning management system, compliance software, analytics dashboard, training automation tool\n\nUse lowercase, semicolon. Do not include use cases, buyer types, or technologies here.",
        
        "technology_delivery": "Based on the {long_company_description} and {long_offering} and {summary}, identify how the offering is delivered or brought to market — i.e., the company's core go-to-market model. This reflects how customers receive or engage with the product or service.\nSelect up to 2–3 delivery tags from the list below that are explicitly stated or clearly implied:\nDelivery Tag --> Explanation\nsoftware (Delivered digitally as software (includes apps, tools, platforms))\nservice (Delivered as a service (human-led or automated, but not productized))\nproduct (Delivered as a physical or digital product (one-time purchase or installed))\nplatform (Connects multiple parties (marketplace, ecosystem, etc.))\nconsulting (Delivered through advisory, expert-led engagements)\nfield-deployed (Requires on-site implementation or servicing)\nintegrated (Delivered as part of or embedded in client systems/workflows)\npartner-delivered (Delivered through partners, integrators, or resellers)\n\nUse lowercase; semicolon-separated.",
        
        "company_description": "Based on the {long_company_description} and {summary}, Provide a structured, 3–5 sentence description of the company's offering. Your answer should clearly include: \n\nWhat the company provides (main product/service) \nWho they serve (customer type, e.g., sales teams, HR departments, clinics) \nWhich industries or market segments they target \nWhat purpose or problem the offering addresses (the \"\"\"\"why\"\"\"\") \nAny notable technologies, service models, or delivery formats \n\nUse a tone like: \n\"Provider of [specific product/service] to [customer type] in [industry/sector], intended to [achieve outcome].\" \n\nUse information only from the company's website and avoid generalities.",
        
        "company_short_description": "Based on the {long_company_description} and {summary} create a short phrase that describes 2 things. What the company offers (Primary offering), what the offering is used for (Primary use case)\nFocus only on the primary result and put keywords first. \nFor example: \nrobotic surgery tools reduce operation mistakes, fraud detection software stops financial theft, contract software organizes legal documents\n\nDo not include vague or broad words. Use language a child can understand. Optimize the response for semantic search",
        
        "industry_category": "Based on the {long_company_description} and {summary}, describe the commercial category the company's offering fits into — how it would be positioned in a software or commercial solution landscape.\nUse standardized terms like:\nMarketing Automation, Sales Enablement Software, Workforce Training Platforms, Compliance Management Tools, Healthcare IT, Cybersecurity Software, Cloud Infrastructure, etc.\n\nIf multiple apply, separate them with a semicolon (;).",
        
        "describe_products_services": "Based on the {long_company_description} and {long_offering} and {summary}, write a single, concise sentence that states what the company provides. Focus strictly on its core deliverables—products, services, or platforms—using clear, functional language. Do not include how the offering works, its features, benefits, or industry context.\nAvoid adjectives, jargon, and abstract phrases. The sentence should be specific, standardized, and matchable across companies for semantic comparison.",
        
        "product_service_features": "Based on the {long_company_description} and {long_offering} and {summary}, extract a semicolon-separated list of 2–5 key product features, service modules, or functional deliverables. Focus on what the company actually provides, not how it works or who it serves. Use specific, noun-based terms where possible (e.g., 'automated claims tracking'; 'real-time analytics'; 'document version control').\nAvoid vague, UI-focused, or benefit-oriented phrases (e.g., 'intuitive dashboard', 'better collaboration').\nReturn only the list — no extra words or punctuation.",
        
        "supply_chain_role": "Based on the {long_company_description} and {long_offering} and {summary}, identify where the company is on the supply chain.\nBased only on the comapany's primary offering select up to 2 tags from the list below that are explicitly stated or clearly implied: \n\nDelivery Tag --> Explanation \nChoose all that are explicitly stated or clearly implied by the company's offerings, business model, or go-to-market structure.\nConsultancy (delivers expert advice or strategic guidance)\nDevelopment (builds physical or software-based products from scratch)\nDistribution (handles logistics, warehousing, or channel operations)\nFinancing (offers funding, underwriting, or financial enablement)\nManufacturing (produces physical goods or equipment)\nRe-seller (sells third-party offerings, often bundled or supported)\n\nUse lowercase; semicolon-separated.",
        
        "target_customers_type": "Visit the {target_customers_description}, identify the type and size of the organization's target customers. Choose from the following standardized categories:\n\nConsumers / Individuals\nStartups\nSmall Businesses\nMid-sized Businesses\nLarge Enterprises\nHospitals / Clinics\nEducation\nPublic Sector (government, non-profits)\n\nIf multiple categories apply, list them using a semicolon (;) separator.\nDo not infer based on the company's product or delivery model (e.g., SaaS). Use only the categories above unless the site clearly specifies a distinct group.",
        
        "target_customers_industries": "Based on the {target_customers_description} and {customers_industries}, identify the commercial sector or industry the company's customers belong to — where the end customers would typically operate in the broader B2B or enterprise landscape.\n\nUse standardized terms like:\nHealthcare Providers, Financial Services, Manufacturing, Retail, Education, Government, Logistics, Telecommunications, etc.\n\nIf multiple sectors apply, separate them with a semicolon (;). Use clear, simple language. Focus on the primary customer sector first and front-load relevant keywords. Optimize the response for semantic search."
    },
    
}